name: Test build

on:
  push:
    branches: [ "master" ]

env:
  CI_FLUTTER_VERSION: '3.16.x'

jobs:
  build-linux-android:
    name: Build Linux and Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: dart run build_runner build
      - run: flutter build linux
      - run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: build/app/outputs/flutter-apk/app-release.apk
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
      - run: flutter pub get
      - run: dart run build_runner build
      - run: flutter build windows
